import pytest

from gateway.agent_runtime.domain.policy import MAX_GATE_ID_LENGTH, PolicyError, parse_policy
from gateway.agent_runtime.domain.types import (
    ChangedPathGate,
    CheckPassedGate,
    CommandIfChangedGate,
    CommandMatchGate,
    JudgeGate,
)

VALID_POLICY = """\
schema_version: "1.0"
policy:
  id: otari/repo-quality
gates:
  - id: no-hand-edited-changelog
    type: changed_path
    enforcement: required
    forbidden: ["CHANGELOG.md"]
    message: CHANGELOG.md is generated by git-cliff at release time.
"""


def test_parses_a_valid_policy() -> None:
    spec = parse_policy(VALID_POLICY, source=".otari-gates.yml")
    assert spec.schema_version == "1.0"
    assert spec.policy_id == "otari/repo-quality"
    assert len(spec.gates) == 1
    gate = spec.gates[0]
    assert isinstance(gate, ChangedPathGate)
    assert gate.id == "no-hand-edited-changelog"
    assert gate.enforcement == "required"
    assert gate.forbidden == ("CHANGELOG.md",)


@pytest.mark.parametrize(
    "broken",
    [
        # Duplicate top-level key.
        'schema_version: "1.0"\nschema_version: "1.0"\npolicy:\n  id: x\ngates: []\n',
        # Duplicate gate id.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: dup\n    type: changed_path\n    enforcement: required\n"
            '    forbidden: ["a"]\n    message: m\n'
            "  - id: dup\n    type: changed_path\n    enforcement: required\n"
            '    forbidden: ["b"]\n    message: m\n'
        ),
        # Unknown top-level field.
        'schema_version: "1.0"\npolicy:\n  id: x\ngates: []\nextra: true\n',
        # Unsupported schema version.
        'schema_version: "9.9"\npolicy:\n  id: x\ngates: []\n',
        # No gates declared.
        'schema_version: "1.0"\npolicy:\n  id: x\ngates: []\n',
        # Unsupported gate type: never silently skipped.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: judge\n    enforcement: required\n    message: m\n"
        ),
        # Missing forbidden list on a command_match gate.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: command_match\n    enforcement: required\n    message: m\n"
        ),
        # A forbidden phrase that is not a valid shell phrase (unbalanced quote).
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: command_match\n    enforcement: required\n"
            '    forbidden: ["git push \\"--force"]\n    message: m\n'
        ),
        # A forbidden phrase that tokenizes to nothing (all whitespace).
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: command_match\n    enforcement: required\n"
            '    forbidden: ["   "]\n    message: m\n'
        ),
        # Missing forbidden list on a changed_path gate.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: changed_path\n    enforcement: required\n    message: m\n"
        ),
        # Invalid enforcement value.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: changed_path\n    enforcement: sometimes\n"
            '    forbidden: ["a"]\n    message: m\n'
        ),
        # Not a YAML mapping at all.
        "- just\n- a\n- list\n",
        # schema_version, type, and enforcement checked via `in` on a set of
        # strings: an unhashable value (YAML's `[]`) raises TypeError there
        # unless isinstance is checked first. Each of these must come back as
        # a PolicyError (422), not an unhandled TypeError (500).
        "schema_version: []\npolicy:\n  id: x\ngates: []\n",
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: []\n    enforcement: required\n"
            '    forbidden: ["a"]\n    message: m\n'
        ),
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: changed_path\n    enforcement: []\n"
            '    forbidden: ["a"]\n    message: m\n'
        ),
        # A numeric mapping key ends up in the same "unknown fields" set as
        # any string keys alongside it; formatting that error must not itself
        # raise (sorting or joining a set that mixes str and int raises
        # TypeError before the intended PolicyError is ever built).
        'schema_version: "1.0"\npolicy:\n  id: x\ngates: []\n42: oops\n',
        # More than one standalone '**' in one glob: bounded so the
        # segment-crossing matcher never needs to try more than one split.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: changed_path\n    enforcement: required\n"
            '    forbidden: ["a/**/b/**/c"]\n    message: m\n'
        ),
        # Missing when_changed on a command_if_changed gate.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: command_if_changed\n    enforcement: required\n"
            '    require: ["make postman"]\n    message: m\n'
        ),
        # Missing require on a command_if_changed gate.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: command_if_changed\n    enforcement: required\n"
            '    when_changed: ["a"]\n    message: m\n'
        ),
        # A require phrase that is not a valid shell phrase.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: command_if_changed\n    enforcement: required\n"
            '    when_changed: ["a"]\n    require: ["make \\"postman"]\n    message: m\n'
        ),
        # A changed_path gate cannot use command_if_changed's field names, now
        # that the accepted field set is per-type rather than shared.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: changed_path\n    enforcement: required\n"
            '    when_changed: ["a"]\n    message: m\n'
        ),
        # A command_if_changed gate cannot use forbidden, for the same reason.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: command_if_changed\n    enforcement: required\n"
            '    forbidden: ["a"]\n    require: ["b"]\n    message: m\n'
        ),
        # Missing verifier on a check_passed gate.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: check_passed\n    enforcement: required\n    message: m\n"
        ),
    ],
)
def test_rejects_malformed_policy(broken: str) -> None:
    with pytest.raises(PolicyError):
        parse_policy(broken, source="test.yml")


def test_rejects_oversized_policy() -> None:
    huge = VALID_POLICY + ("# padding\n" * 200_000)
    with pytest.raises(PolicyError):
        parse_policy(huge, source="test.yml")


def test_accepts_a_gate_id_at_the_length_limit() -> None:
    """MAX_GATE_ID_LENGTH is shared with JudgeVerdictRequest.gate_id (routes/hooks.py):

    every id this build accepts must be one a verdict can round-trip, so the
    boundary itself (not just one past it) needs its own coverage.
    """
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        f"  - id: {'g' * MAX_GATE_ID_LENGTH}\n    type: judge\n"
        "    enforcement: advisory\n    rubric: r\n    message: m\n"
    )
    spec = parse_policy(policy, source="test.yml")
    assert len(spec.gates[0].id) == MAX_GATE_ID_LENGTH


def test_rejects_a_gate_id_over_the_length_limit() -> None:
    """Without this, a policy accepted at parse time could name a judge gate whose

    id `otari hook` can never actually submit a verdict for
    (`JudgeVerdictRequest.gate_id` caps at the same `MAX_GATE_ID_LENGTH`):
    the whole `/hooks/check` request would 422 on that one field, fail-open,
    taking every other gate in the same policy, mechanical and required
    ones included, down with it.
    """
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        f"  - id: {'g' * (MAX_GATE_ID_LENGTH + 1)}\n    type: judge\n"
        "    enforcement: advisory\n    rubric: r\n    message: m\n"
    )
    with pytest.raises(PolicyError, match="longer than"):
        parse_policy(policy, source="test.yml")


def test_duplicate_forbidden_globs_collapse_to_one() -> None:
    """A repeated glob matches nothing a single copy wouldn't, and multiplies

    the Hook Server's per-request match work for zero effect on the result;
    review caught a request built from 2,500 copies of one forbidden glob
    that took seconds to evaluate before this collapsed at parse time.
    """
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: changed_path\n    enforcement: required\n"
        '    forbidden: ["a", "a", "b", "a"]\n    message: m\n'
    )
    spec = parse_policy(policy, source="test.yml")
    gate = spec.gates[0]
    assert isinstance(gate, ChangedPathGate)
    assert gate.forbidden == ("a", "b")


def test_parses_a_valid_command_match_policy() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: no-force-push\n    type: command_match\n    enforcement: required\n"
        '    forbidden: ["git push --force", "git push -f"]\n    message: m\n'
    )
    spec = parse_policy(policy, source="test.yml")
    assert len(spec.gates) == 1
    gate = spec.gates[0]
    assert isinstance(gate, CommandMatchGate)
    assert gate.forbidden == ("git push --force", "git push -f")


def test_duplicate_forbidden_phrases_collapse_to_one() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: command_match\n    enforcement: required\n"
        '    forbidden: ["npm", "npm", "yarn"]\n    message: m\n'
    )
    spec = parse_policy(policy, source="test.yml")
    gate = spec.gates[0]
    assert isinstance(gate, CommandMatchGate)
    assert gate.forbidden == ("npm", "yarn")


def test_parses_a_valid_command_if_changed_policy() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: openapi-needs-postman\n    type: command_if_changed\n    enforcement: required\n"
        '    when_changed: ["docs/public/openapi.json"]\n    require: ["make postman"]\n    message: m\n'
    )
    spec = parse_policy(policy, source="test.yml")
    assert len(spec.gates) == 1
    gate = spec.gates[0]
    assert isinstance(gate, CommandIfChangedGate)
    assert gate.when_changed == ("docs/public/openapi.json",)
    assert gate.require == ("make postman",)


def test_duplicate_when_changed_globs_and_require_phrases_collapse_to_one() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: command_if_changed\n    enforcement: required\n"
        '    when_changed: ["a", "a", "b"]\n    require: ["c", "c"]\n    message: m\n'
    )
    spec = parse_policy(policy, source="test.yml")
    gate = spec.gates[0]
    assert isinstance(gate, CommandIfChangedGate)
    assert gate.when_changed == ("a", "b")
    assert gate.require == ("c",)


def test_parses_a_valid_judge_policy() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: follows-error-handling-pattern\n    type: judge\n    enforcement: advisory\n"
        "    rubric: Does this change follow the repository's error-handling conventions?\n"
        "    message: m\n"
    )
    spec = parse_policy(policy, source="test.yml")
    assert len(spec.gates) == 1
    gate = spec.gates[0]
    assert isinstance(gate, JudgeGate)
    assert gate.enforcement == "advisory"
    assert gate.rubric == "Does this change follow the repository's error-handling conventions?"


def test_judge_gate_rejects_required_enforcement() -> None:
    """A model's verdict is never reproducible enough to block a required gate.

    Rejected at parse time so a mistaken `enforcement: required` is a 422
    when the policy is loaded, not a gate that silently blocks on a model's
    say-so the first time it happens to fail.
    """
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: judge\n    enforcement: required\n    rubric: r\n    message: m\n"
    )
    with pytest.raises(PolicyError, match="judge"):
        parse_policy(policy, source="test.yml")


def test_judge_gate_requires_a_non_empty_rubric() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: judge\n    enforcement: advisory\n    rubric: '   '\n    message: m\n"
    )
    with pytest.raises(PolicyError, match="rubric"):
        parse_policy(policy, source="test.yml")


def test_judge_gate_rejects_an_oversized_rubric() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        f"  - id: g\n    type: judge\n    enforcement: advisory\n    rubric: {'x' * 20_000}\n    message: m\n"
    )
    with pytest.raises(PolicyError, match="rubric"):
        parse_policy(policy, source="test.yml")


def test_judge_gate_when_changed_defaults_to_always_applying() -> None:
    """A judge gate that never mentions `when_changed` keeps its pre-field behavior."""
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: judge\n    enforcement: advisory\n    rubric: r\n    message: m\n"
    )
    spec = parse_policy(policy, source="test.yml")
    gate = spec.gates[0]
    assert isinstance(gate, JudgeGate)
    assert gate.when_changed == ()


def test_judge_gate_parses_when_changed_globs() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: judge\n    enforcement: advisory\n    rubric: r\n"
        "    when_changed: [src/**]\n    message: m\n"
    )
    spec = parse_policy(policy, source="test.yml")
    gate = spec.gates[0]
    assert isinstance(gate, JudgeGate)
    assert gate.when_changed == ("src/**",)


def test_judge_gate_rejects_an_explicitly_empty_when_changed() -> None:
    """Unlike an omitted `when_changed`, an explicit empty list is a 422, not "always applies".

    An author who writes `when_changed: []` almost certainly meant
    something; guessing which is worse than refusing it, the same rule
    `command_if_changed`'s own `when_changed` already follows.
    """
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: judge\n    enforcement: advisory\n    rubric: r\n"
        "    when_changed: []\n    message: m\n"
    )
    with pytest.raises(PolicyError, match="when_changed"):
        parse_policy(policy, source="test.yml")


def test_judge_gate_judge_cli_defaults_to_none() -> None:
    """A judge gate that never mentions `judge_cli` keeps its pre-field behavior: no preference."""
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: judge\n    enforcement: advisory\n    rubric: r\n    message: m\n"
    )
    spec = parse_policy(policy, source="test.yml")
    gate = spec.gates[0]
    assert isinstance(gate, JudgeGate)
    assert gate.judge_cli is None


def test_judge_gate_accepts_a_bare_judge_cli_string() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: judge\n    enforcement: advisory\n    rubric: r\n"
        "    judge_cli: codex\n    message: m\n"
    )
    spec = parse_policy(policy, source="test.yml")
    gate = spec.gates[0]
    assert isinstance(gate, JudgeGate)
    assert gate.judge_cli == ("codex",)


def test_judge_gate_accepts_an_ordered_judge_cli_list_deduplicated() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: judge\n    enforcement: advisory\n    rubric: r\n"
        "    judge_cli: [codex, claude, codex]\n    message: m\n"
    )
    spec = parse_policy(policy, source="test.yml")
    gate = spec.gates[0]
    assert isinstance(gate, JudgeGate)
    assert gate.judge_cli == ("codex", "claude")


def test_judge_gate_rejects_an_unsupported_judge_cli() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: judge\n    enforcement: advisory\n    rubric: r\n"
        "    judge_cli: gemini\n    message: m\n"
    )
    with pytest.raises(PolicyError, match="judge_cli"):
        parse_policy(policy, source="test.yml")


def test_judge_gate_rejects_an_explicitly_empty_judge_cli_list() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: judge\n    enforcement: advisory\n    rubric: r\n"
        "    judge_cli: []\n    message: m\n"
    )
    with pytest.raises(PolicyError, match="judge_cli"):
        parse_policy(policy, source="test.yml")


def test_parses_a_valid_check_passed_policy() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: no-leftover-conflict-markers\n    type: check_passed\n    enforcement: required\n"
        "    verifier: .otari-gates/verifiers/no-conflict-markers.sh\n    message: m\n"
    )
    spec = parse_policy(policy, source="test.yml")
    assert len(spec.gates) == 1
    gate = spec.gates[0]
    assert isinstance(gate, CheckPassedGate)
    assert gate.enforcement == "required"
    assert gate.verifier == ".otari-gates/verifiers/no-conflict-markers.sh"


def test_check_passed_gate_accepts_required_enforcement() -> None:
    """Unlike judge, a verifier's exit code is reproducible, so required is allowed."""
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: check_passed\n    enforcement: required\n"
        "    verifier: v.sh\n    message: m\n"
    )
    spec = parse_policy(policy, source="test.yml")
    gate = spec.gates[0]
    assert isinstance(gate, CheckPassedGate)
    assert gate.enforcement == "required"


def test_check_passed_gate_accepts_advisory_enforcement() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: check_passed\n    enforcement: advisory\n"
        "    verifier: v.sh\n    message: m\n"
    )
    spec = parse_policy(policy, source="test.yml")
    gate = spec.gates[0]
    assert isinstance(gate, CheckPassedGate)
    assert gate.enforcement == "advisory"


def test_check_passed_gate_requires_a_non_empty_verifier() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: check_passed\n    enforcement: required\n"
        "    verifier: '   '\n    message: m\n"
    )
    with pytest.raises(PolicyError, match="verifier"):
        parse_policy(policy, source="test.yml")


def test_check_passed_gate_rejects_an_absolute_verifier_path() -> None:
    """A verifier is a repo-relative path; an absolute one is not one this build runs against a repo root."""
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: check_passed\n    enforcement: required\n"
        "    verifier: /etc/passwd\n    message: m\n"
    )
    with pytest.raises(PolicyError, match="repo-relative"):
        parse_policy(policy, source="test.yml")


def test_check_passed_gate_rejects_a_verifier_with_a_nul_byte() -> None:
    """A NUL byte reaching subprocess as an argv element raises ValueError; caught here as a clean 422 instead."""
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        '  - id: g\n    type: check_passed\n    enforcement: required\n    verifier: "v\\0.sh"\n    message: m\n'
    )
    with pytest.raises(PolicyError, match="NUL"):
        parse_policy(policy, source="test.yml")


def test_check_passed_gate_rejects_an_oversized_verifier() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        f"  - id: g\n    type: check_passed\n    enforcement: required\n    verifier: {'v' * 5_000}\n"
        "    message: m\n"
    )
    with pytest.raises(PolicyError, match="verifier"):
        parse_policy(policy, source="test.yml")


def test_check_passed_gate_when_changed_defaults_to_always_applying() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: check_passed\n    enforcement: required\n    verifier: v.sh\n    message: m\n"
    )
    spec = parse_policy(policy, source="test.yml")
    gate = spec.gates[0]
    assert isinstance(gate, CheckPassedGate)
    assert gate.when_changed == ()


def test_check_passed_gate_parses_when_changed_globs() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: check_passed\n    enforcement: required\n    verifier: v.sh\n"
        "    when_changed: [src/**]\n    message: m\n"
    )
    spec = parse_policy(policy, source="test.yml")
    gate = spec.gates[0]
    assert isinstance(gate, CheckPassedGate)
    assert gate.when_changed == ("src/**",)


def test_check_passed_gate_rejects_an_explicitly_empty_when_changed() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        "  - id: g\n    type: check_passed\n    enforcement: required\n    verifier: v.sh\n"
        "    when_changed: []\n    message: m\n"
    )
    with pytest.raises(PolicyError, match="when_changed"):
        parse_policy(policy, source="test.yml")


def test_unhashable_yaml_mapping_key_is_rejected_not_a_500() -> None:
    """YAML's explicit-key syntax permits a sequence as a mapping key, which

    Python cannot hash. The duplicate-key check must not let that raise a
    bare TypeError in place of the PolicyError every other malformed policy
    gets.
    """
    policy = 'schema_version: "1.0"\npolicy:\n  id: x\ngates: []\n? [a, b]\n: c\n'
    with pytest.raises(PolicyError):
        parse_policy(policy, source="test.yml")
