import pytest

from gateway.agent_runtime.domain.policy import PolicyError, parse_policy
from gateway.agent_runtime.domain.types import ChangedPathGate, CommandMatchGate

VALID_POLICY = """\
schema_version: "1.0"
policy:
  id: otari/repo-quality
gates:
  - id: no-hand-edited-changelog
    type: changed_path
    enforcement: required
    forbidden: ["CHANGELOG.md"]
    message: CHANGELOG.md is generated by git-cliff at release time.
"""


def test_parses_a_valid_policy() -> None:
    spec = parse_policy(VALID_POLICY, source=".otari-gates.yml")
    assert spec.schema_version == "1.0"
    assert spec.policy_id == "otari/repo-quality"
    assert len(spec.gates) == 1
    gate = spec.gates[0]
    assert isinstance(gate, ChangedPathGate)
    assert gate.id == "no-hand-edited-changelog"
    assert gate.enforcement == "required"
    assert gate.forbidden == ("CHANGELOG.md",)


@pytest.mark.parametrize(
    "broken",
    [
        # Duplicate top-level key.
        'schema_version: "1.0"\nschema_version: "1.0"\npolicy:\n  id: x\ngates: []\n',
        # Duplicate gate id.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: dup\n    type: changed_path\n    enforcement: required\n"
            '    forbidden: ["a"]\n    message: m\n'
            "  - id: dup\n    type: changed_path\n    enforcement: required\n"
            '    forbidden: ["b"]\n    message: m\n'
        ),
        # Unknown top-level field.
        'schema_version: "1.0"\npolicy:\n  id: x\ngates: []\nextra: true\n',
        # Unsupported schema version.
        'schema_version: "9.9"\npolicy:\n  id: x\ngates: []\n',
        # No gates declared.
        'schema_version: "1.0"\npolicy:\n  id: x\ngates: []\n',
        # Unsupported gate type: never silently skipped.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: judge\n    enforcement: required\n    message: m\n"
        ),
        # Missing forbidden list on a command_match gate.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: command_match\n    enforcement: required\n    message: m\n"
        ),
        # A forbidden phrase that is not a valid shell phrase (unbalanced quote).
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            '  - id: g\n    type: command_match\n    enforcement: required\n'
            '    forbidden: ["git push \\"--force"]\n    message: m\n'
        ),
        # A forbidden phrase that tokenizes to nothing (all whitespace).
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            '  - id: g\n    type: command_match\n    enforcement: required\n'
            '    forbidden: ["   "]\n    message: m\n'
        ),
        # Missing forbidden list on a changed_path gate.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: changed_path\n    enforcement: required\n    message: m\n"
        ),
        # Invalid enforcement value.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: changed_path\n    enforcement: sometimes\n"
            '    forbidden: ["a"]\n    message: m\n'
        ),
        # Not a YAML mapping at all.
        "- just\n- a\n- list\n",
        # schema_version, type, and enforcement checked via `in` on a set of
        # strings: an unhashable value (YAML's `[]`) raises TypeError there
        # unless isinstance is checked first. Each of these must come back as
        # a PolicyError (422), not an unhandled TypeError (500).
        'schema_version: []\npolicy:\n  id: x\ngates: []\n',
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: []\n    enforcement: required\n"
            '    forbidden: ["a"]\n    message: m\n'
        ),
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: changed_path\n    enforcement: []\n"
            '    forbidden: ["a"]\n    message: m\n'
        ),
        # A numeric mapping key ends up in the same "unknown fields" set as
        # any string keys alongside it; formatting that error must not itself
        # raise (sorting or joining a set that mixes str and int raises
        # TypeError before the intended PolicyError is ever built).
        'schema_version: "1.0"\npolicy:\n  id: x\ngates: []\n42: oops\n',
        # More than one standalone '**' in one glob: bounded so the
        # segment-crossing matcher never needs to try more than one split.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            '  - id: g\n    type: changed_path\n    enforcement: required\n'
            '    forbidden: ["a/**/b/**/c"]\n    message: m\n'
        ),
    ],
)
def test_rejects_malformed_policy(broken: str) -> None:
    with pytest.raises(PolicyError):
        parse_policy(broken, source="test.yml")


def test_rejects_oversized_policy() -> None:
    huge = VALID_POLICY + ("# padding\n" * 200_000)
    with pytest.raises(PolicyError):
        parse_policy(huge, source="test.yml")


def test_duplicate_forbidden_globs_collapse_to_one() -> None:
    """A repeated glob matches nothing a single copy wouldn't, and multiplies

    the Hook Server's per-request match work for zero effect on the result;
    review caught a request built from 2,500 copies of one forbidden glob
    that took seconds to evaluate before this collapsed at parse time.
    """
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        '  - id: g\n    type: changed_path\n    enforcement: required\n'
        '    forbidden: ["a", "a", "b", "a"]\n    message: m\n'
    )
    spec = parse_policy(policy, source="test.yml")
    assert spec.gates[0].forbidden == ("a", "b")


def test_parses_a_valid_command_match_policy() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        '  - id: no-force-push\n    type: command_match\n    enforcement: required\n'
        '    forbidden: ["git push --force", "git push -f"]\n    message: m\n'
    )
    spec = parse_policy(policy, source="test.yml")
    assert len(spec.gates) == 1
    gate = spec.gates[0]
    assert isinstance(gate, CommandMatchGate)
    assert gate.forbidden == ("git push --force", "git push -f")


def test_duplicate_forbidden_phrases_collapse_to_one() -> None:
    policy = (
        'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
        '  - id: g\n    type: command_match\n    enforcement: required\n'
        '    forbidden: ["npm", "npm", "yarn"]\n    message: m\n'
    )
    spec = parse_policy(policy, source="test.yml")
    assert spec.gates[0].forbidden == ("npm", "yarn")


def test_unhashable_yaml_mapping_key_is_rejected_not_a_500() -> None:
    """YAML's explicit-key syntax permits a sequence as a mapping key, which

    Python cannot hash. The duplicate-key check must not let that raise a
    bare TypeError in place of the PolicyError every other malformed policy
    gets.
    """
    policy = 'schema_version: "1.0"\npolicy:\n  id: x\ngates: []\n? [a, b]\n: c\n'
    with pytest.raises(PolicyError):
        parse_policy(policy, source="test.yml")
