import pytest

from gateway.agent_runtime.domain.policy import PolicyError, parse_policy
from gateway.agent_runtime.domain.types import ChangedPathGate

VALID_POLICY = """\
schema_version: "1.0"
policy:
  id: otari/repo-quality
gates:
  - id: no-hand-edited-changelog
    type: changed_path
    enforcement: required
    forbidden: ["CHANGELOG.md"]
    message: CHANGELOG.md is generated by git-cliff at release time.
"""


def test_parses_a_valid_policy() -> None:
    spec = parse_policy(VALID_POLICY, source=".otari-gates.yml")
    assert spec.schema_version == "1.0"
    assert spec.policy_id == "otari/repo-quality"
    assert len(spec.gates) == 1
    gate = spec.gates[0]
    assert isinstance(gate, ChangedPathGate)
    assert gate.id == "no-hand-edited-changelog"
    assert gate.enforcement == "required"
    assert gate.forbidden == ("CHANGELOG.md",)


@pytest.mark.parametrize(
    "broken",
    [
        # Duplicate top-level key.
        'schema_version: "1.0"\nschema_version: "1.0"\npolicy:\n  id: x\ngates: []\n',
        # Duplicate gate id.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: dup\n    type: changed_path\n    enforcement: required\n"
            '    forbidden: ["a"]\n    message: m\n'
            "  - id: dup\n    type: changed_path\n    enforcement: required\n"
            '    forbidden: ["b"]\n    message: m\n'
        ),
        # Unknown top-level field.
        'schema_version: "1.0"\npolicy:\n  id: x\ngates: []\nextra: true\n',
        # Unsupported schema version.
        'schema_version: "9.9"\npolicy:\n  id: x\ngates: []\n',
        # No gates declared.
        'schema_version: "1.0"\npolicy:\n  id: x\ngates: []\n',
        # Unsupported gate type: never silently skipped.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: command_match\n    enforcement: required\n    message: m\n"
        ),
        # Missing forbidden list on a changed_path gate.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: changed_path\n    enforcement: required\n    message: m\n"
        ),
        # Invalid enforcement value.
        (
            'schema_version: "1.0"\npolicy:\n  id: x\ngates:\n'
            "  - id: g\n    type: changed_path\n    enforcement: sometimes\n"
            '    forbidden: ["a"]\n    message: m\n'
        ),
        # Not a YAML mapping at all.
        "- just\n- a\n- list\n",
    ],
)
def test_rejects_malformed_policy(broken: str) -> None:
    with pytest.raises(PolicyError):
        parse_policy(broken, source="test.yml")


def test_rejects_oversized_policy() -> None:
    huge = VALID_POLICY + ("# padding\n" * 200_000)
    with pytest.raises(PolicyError):
        parse_policy(huge, source="test.yml")
