from gateway.agent_runtime.domain.evaluators import evaluate_changed_path
from gateway.agent_runtime.domain.types import ChangedPathEvidence, ChangedPathGate, Outcome


def _gate(**overrides: object) -> ChangedPathGate:
    defaults: dict[str, object] = {
        "id": "no-hand-edited-changelog",
        "enforcement": "required",
        "forbidden": ("CHANGELOG.md",),
        "message": "CHANGELOG.md is generated by git-cliff at release time.",
    }
    defaults.update(overrides)
    return ChangedPathGate(**defaults)  # type: ignore[arg-type]


def test_pass_when_no_forbidden_path_changed() -> None:
    result = evaluate_changed_path(_gate(), ChangedPathEvidence(changed_paths=("README.md", "src/gateway/cli.py")))
    assert result.outcome is Outcome.PASS
    assert not result.outcome.is_blocking


def test_fail_when_a_forbidden_path_changed() -> None:
    evidence = ChangedPathEvidence(changed_paths=("CHANGELOG.md",))
    result = evaluate_changed_path(_gate(), evidence)
    assert result.outcome is Outcome.FAIL
    assert result.outcome.is_blocking
    assert "CHANGELOG.md" in (result.detail or "")


def test_unknown_when_evidence_was_not_collected() -> None:
    result = evaluate_changed_path(_gate(), None)
    assert result.outcome is Outcome.UNKNOWN
    assert result.outcome.is_blocking, "unknown must block a required gate, never pass silently"


def test_star_does_not_cross_a_path_segment() -> None:
    gate = _gate(forbidden=("src/*.py",))
    # A single '*' must not match the nested file: only a direct child of src/ counts.
    result = evaluate_changed_path(gate, ChangedPathEvidence(changed_paths=("src/gateway/cli.py",)))
    assert result.outcome is Outcome.PASS


def test_double_star_crosses_path_segments() -> None:
    gate = _gate(forbidden=("src/**",))
    result = evaluate_changed_path(gate, ChangedPathEvidence(changed_paths=("src/gateway/cli.py",)))
    assert result.outcome is Outcome.FAIL


def test_advisory_gate_does_not_block_required() -> None:
    gate = _gate(enforcement="advisory")
    result = evaluate_changed_path(gate, ChangedPathEvidence(changed_paths=("CHANGELOG.md",)))
    assert result.outcome is Outcome.FAIL
    assert result.enforcement == "advisory"
